### ISSUE TITLE
i got this error bro

### ISSUE THREAD

**Issue by Lordakim** [superdanglyde/Card-Checker-Stripe-#1]
python check.py
File : cc_file
Traceback (most recent call last):
  File "check.py", line 101, in <module>
    Checker()
  File "check.py", line 11, in __init__
    cc_file = input('File : ')
  File "<string>", line 1, in <module>
NameError: name 'cc_file' is not defined

**Comment by theblackdna** [comment]
Sorry for that, I'm still fixing the codes :)

**Comment by Lordakim** [comment]
can i have your email bro to instant msg you or whatsapp
